name = "hello-hacker"
license = "MIT"
licenselink = "https://github.com/Matir/hugo-theme-hello-hacker/blob/main/LICENSE.md"
description = "A simple theme for Hugo. That's it."
tags = ["blog", "clean", "customizable", "dark", "highlighting", "light", "minimal", "monochromatic", "multilingual", "personal", "responsive", "simple", "technical"]
features = ["blog", "shortcode", "syntax highlighting"]
min_version = 0.30

[author]
  name = "David Tomaschik"
  homepage = "https://systemoverlord.com"

[original]
  name = "hello-friend"
  homepage = "https://github.com/panr/hugo-theme-hello-friend"
  repo = "https://github.com/panr/hugo-theme-hello-friend"
